---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/projectcalico/vpp-dataplane/refs/heads/release/v3.29.0/yaml/generated/calico-vpp-kind.yaml

patchesStrategicMerge:
  - patch.yaml
