---
apiVersion: v1
kind: ConfigMap
metadata:
  name: calico-vpp-config
  namespace: calico-vpp-dataplane
data:
  CALICOVPP_INITIAL_CONFIG: |-
    {
      "vppStartupSleepSeconds": 1,
      "corePattern": "/var/lib/vpp/vppcore.%e.%p",
      "redirectToHostRules": [
        {
          "proto": "udp",
          "port": 53,
          "ip": "172.18.0.1"
        },
        {
          "proto": "tcp",
          "port": 53,
          "ip": "172.18.0.1"
        }
      ]
    }
